### ISSUE TITLE
EvenUneven/EvenUneven: user interface + EvenUneven: стиль

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [nzerg/LevelUp#6]
1. Лучше поставить у else скобки, и уж точно не писать все в одну линию - выглядит нечитаемо. 
Если вы используете if/then/else без скобок, то лучше у всей конструкции скобки не ставить.
2. Пользователю сообщается, что число должно быть больше 0, но на деле при введении числа  меньше 0 ничего не происходит. Это неконсистентное поведение

**Comment by nzerg** [comment]
1/ исправил
2. Добавил еще одно условие if для проверки n

**Comment by anastasiya-solodkaya** [comment]
Вообще в EvenUnevenTernar тоже проблема с n < 0. Вообще ое, на будущее, там у вас есть переменная m, можно ее не заводить, а просто писать

```
if (n % 2 == 0) {
    ....
}
```
