### ISSUE TITLE
Neraten/NearTen2 - стиль

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [nzerg/LevelUp#9]
Тут тожзе проблемы со стилем в конструкции if-then-else

**Comment by nzerg** [comment]
добавил скобки, впредь буду всегда их ставить

**Comment by anastasiya-solodkaya** [comment]
Ну они и правда не везде обязательны, например конструкция 

...
if (radius < 0) return false;
...

смотрится очень даже хорошо :)
